let ITEM_GUN = 1;
let ITEM_DESERT_EAGLE = 110;
let ITEM_SHOTGUN = 15;
let ITEM_MINIGUN = 16;
let ITEM_PLASMA_LAUNCHER = 17;
let ITEM_RED_PISTOLS = 20;
let ITEM_RED_SHOTGUN = 21;
let ITEM_GREEN_GUN = 23;
let ITEM_SWORD = 24;
let ITEM_ROCKET_LAUNCHER = 26;
let ITEM_RAINBOW_PISTOLS = 29;
let ITEM_LASER_GUN = 33;
let ITEM_PLASMA_PISTOL = 35;
let ITEM_ROCKET_SHOTGUN = 36;
let ITEM_HORN = 37;
let ITEM_AMMO = 2;
let ITEM_PLASMA = 18;
let ITEM_RED_PLASMA = 19;
let ITEM_GREEN_AMMO = 25;
let ITEM_ROCKET = 27;
let ITEM_RAINBOW_AMMO = 30;
let ITEM_HEALTH = 3;
let ITEM_FUEL = 4;
let ITEM_SHIELD = 22;
let ITEM_HEALTH_GREEN = 28;
let ITEM_SHIELD_GREEN = 31;
let ITEM_SHIELD_RAINBOW = 32;
let ITEM_CANNED_MEAT = 7;
let ITEM_ORANGE = 8;
let ITEM_APPLE = 9;
let ITEM_CHERRIES = 10;
let ITEM_CHICKEN_LEG = 13;
let ITEM_CHOCOLATE = 14;
let ITEM_WATER = 6;
let ITEM_COLA = 11;
let ITEM_MILK = 12;
let ITEM_MONEY = 5;
let ITEM_BOSSIFIER = 34;
let ITEM_APPLE_CORE = 100;
let ITEM_FISH_BONE = 101;
let ITEM_EMPTY_BOTTLE = 102;
let ITEM_TIN_CAN = 103;
let ITEM_OLD_SHOE = 104;
let ITEM_BENT_FORK = 105;
let ITEM_CRUMPLED_PAPER = 106;
let ITEM_DEAD_BATTERY = 107;
let ITEM_JUNK_CANNON = 108;
let ITEM_REVOLVER = 111;
let ITEM_STICK = 112;
let ITEM_STONE = 113;
let ITEM_BOSSIFIER_REGULAR = 120;
let ITEM_BOSSIFIER_SHOOTING = 121;
let ITEM_BOSSIFIER_RED = 122;
let ITEM_BOSSIFIER_SWORD = 123;
let ITEM_BOSSIFIER_ROCKET = 124;
let ITEM_BOSSIFIER_LASER = 125;
let ITEM_SHIELD_GRAY = 126;
let ITEM_KALASHNIKOV = 114;
let ITEM_BOSSIFIER_DESERT = 127;
let ITEM_VENOM = 128;
let ITEM_VENOM_SHOTGUN = 129;
let ITEM_ACID_SMG = 130;
let ITEM_VENOM_DUAL_SHOTGUNS = 131;
let ITEM_SNAKE_STAFF = 132;
let ITEM_BOSSIFIER_MUMMY = 133;
let ITEM_BOSSIFIER_SHADOW = 134;
let ITEM_BOSSIFIER_ANUBIS = 135
let ITEM_MUMMY_SHOTGUN = 140;
let ITEM_MUMMY_PISTOLS = 141;
let ITEM_SHADOW_SHIELD = 142;
let ITEM_SHADOW_STAFF = 143;
let ITEM_SHADOW_DUAL_SHOTGUNS = 144;
let ITEM_ANUBIS_SANDSTORM_STAFF = 145;
let ITEM_ANUBIS_REGEN_SHIELD = 146;
let ITEM_ANUBIS_PUNISHER_ROD = 147;
let ITEM_DIARY = 150;
let ITEMS_BOSSIFIERS = [
	ITEM_BOSSIFIER_REGULAR,
	ITEM_BOSSIFIER_SHOOTING,
	ITEM_BOSSIFIER_RED,
	ITEM_BOSSIFIER_SWORD,
	ITEM_BOSSIFIER_ROCKET,
	ITEM_BOSSIFIER_LASER,
	ITEM_BOSSIFIER_DESERT,
	ITEM_BOSSIFIER_MUMMY,
	ITEM_BOSSIFIER_SHADOW,
	ITEM_BOSSIFIER_ANUBIS,
];
let ITEMS_JUNK = [
	ITEM_APPLE_CORE,
	ITEM_FISH_BONE,
	ITEM_EMPTY_BOTTLE,
	ITEM_TIN_CAN,
	ITEM_OLD_SHOE,
	ITEM_CRUMPLED_PAPER,
	ITEM_DEAD_BATTERY
];
ITEMS_AMMOS = [
	ITEM_AMMO,
	ITEM_PLASMA,
	ITEM_RED_PLASMA,
	ITEM_ROCKET,
	ITEM_RAINBOW_AMMO,
	ITEM_VENOM
];
ITEMS_GUNS = [
	ITEM_GUN,
	ITEM_DESERT_EAGLE,
	ITEM_SHOTGUN,
	ITEM_MINIGUN,
	ITEM_PLASMA_LAUNCHER,
	ITEM_PLASMA_PISTOL,
	ITEM_REVOLVER,
	ITEM_KALASHNIKOV,
	ITEM_RED_PISTOLS,
	ITEM_RED_SHOTGUN,
	ITEM_MUMMY_PISTOLS,
	ITEM_MUMMY_SHOTGUN,
	ITEM_GREEN_GUN,
	ITEM_SHADOW_STAFF,
	ITEM_SHADOW_DUAL_SHOTGUNS,
	ITEM_ROCKET_LAUNCHER,
	ITEM_ROCKET_SHOTGUN,
	ITEM_ANUBIS_SANDSTORM_STAFF,
	ITEM_ANUBIS_PUNISHER_ROD,
	ITEM_RAINBOW_PISTOLS,
	ITEM_LASER_GUN,
	ITEM_JUNK_CANNON,
	ITEM_SNAKE_STAFF
];
ITEMS_MELEE = [
	ITEM_STICK,
	ITEM_SWORD,
	ITEM_HORN
];
ITEMS_FOODS = [
	ITEM_CANNED_MEAT,
	ITEM_ORANGE,
	ITEM_APPLE,
	ITEM_CHICKEN_LEG,
	ITEM_CHOCOLATE
];
ITEMS_DRINKS = [
	ITEM_WATER,
	ITEM_COLA,
	ITEM_MILK
];