let ITEM_GUN = 1;
let ITEM_AMMO = 2;
let ITEM_DESERT_EAGLE = 110;
let ITEM_SHOTGUN = 15;
let ITEM_MINIGUN = 16;
let ITEM_PLASMA_LAUNCHER = 17;
let ITEM_RED_PISTOLS = 20;
let ITEM_RED_SHOTGUN = 21;
let ITEM_GREEN_GUN = 23;
let ITEM_SWORD = 24;
let ITEM_ROCKET_LAUNCHER = 26;
let ITEM_RAINBOW_PISTOLS = 29;
let ITEM_LASER_GUN = 33;
let ITEM_PLASMA_PISTOL = 35;
let ITEM_ROCKET_SHOTGUN = 36;
let ITEM_HORN = 37;
let ITEM_PLASMA = 18;
let ITEM_RED_PLASMA = 19;
let ITEM_GREEN_AMMO = 25;
let ITEM_ROCKET = 27;
let ITEM_RAINBOW_AMMO = 30;
let ITEM_HEALTH = 3;
let ITEM_FUEL = 4;
let ITEM_SHIELD = 22;
let ITEM_HEALTH_GREEN = 28;
let ITEM_SHIELD_GREEN = 31;
let ITEM_SHIELD_RAINBOW = 32;
let ITEM_CANNED_MEAT = 7;
let ITEM_ORANGE = 8;
let ITEM_APPLE = 9;
let ITEM_CHERRIES = 10;
let ITEM_CHICKEN_LEG = 13;
let ITEM_CHOCOLATE = 14;
let ITEM_WATER = 6;
let ITEM_COLA = 11;
let ITEM_MILK = 12;
let ITEM_MONEY = 5;
let ITEM_BOSSIFIER = 34;
let ITEM_APPLE_CORE = 100;
let ITEM_FISH_BONE = 101;
let ITEM_EMPTY_BOTTLE = 102;
let ITEM_TIN_CAN = 103;
let ITEM_OLD_SHOE = 104;
let ITEM_BENT_FORK = 105;
let ITEM_CRUMPLED_PAPER = 106;
let ITEM_DEAD_BATTERY = 107;
let ITEM_JUNK_CANNON = 108;
let ITEM_REVOLVER = 111;
let ITEM_STICK = 112;
let ITEM_STONE = 113;
let ITEM_BOSSIFIER_REGULAR = 120;
let ITEM_BOSSIFIER_SHOOTING = 121;
let ITEM_BOSSIFIER_RED = 122;
let ITEM_BOSSIFIER_SWORD = 123;
let ITEM_BOSSIFIER_ROCKET = 124;
let ITEM_BOSSIFIER_LASER = 125;
let ITEM_SHIELD_GRAY = 126;
let ITEM_KALASHNIKOV = 114;
let ITEM_BOSSIFIER_DESERT = 127;
let ITEM_VENOM = 128;
let ITEM_VENOM_SHOTGUN = 129;
let ITEM_ACID_SMG = 130;
let ITEM_VENOM_DUAL_SHOTGUNS = 131;
let ITEM_SNAKE_STAFF = 132;
let ITEM_BOSSIFIER_MUMMY = 133;
let ITEM_BOSSIFIER_SHADOW = 134;
let ITEM_BOSSIFIER_ANUBIS = 135
let ITEM_MUMMY_SHOTGUN = 140;
let ITEM_MUMMY_PISTOLS = 141;
let ITEM_SHADOW_SHIELD = 142;
let ITEM_SHADOW_STAFF = 143;
let ITEM_SHADOW_DUAL_SHOTGUNS = 144;
let ITEM_ANUBIS_SANDSTORM_STAFF = 145;
let ITEM_ANUBIS_REGEN_SHIELD = 146;
let ITEM_ANUBIS_PUNISHER_ROD = 147;
let ITEM_DIARY = 150;
let ITEM_SURVIVOR_NOTE = 151;
let ITEM_CACTUS_JUICE = 152;
let ITEM_HONEY = 153;
let ITEM_BOSSIFIER_SNOW = 160;
let ITEM_BOSSIFIER_USHANKA = 161;
let ITEM_BOSSIFIER_SNOWMAN = 162;
let ITEM_BOSSIFIER_KRAMPUS = 163;
let ITEM_BOSSIFIER_BLOOD = 164;
let ITEM_BOSSIFIER_PUMPKIN_SKELETON = 165;
let ITEM_PP_SH = 250;
let ITEM_MOSIN_RIFLE = 251;
let ITEM_ROCKET_PISTOL = 252;
let ITEM_FLAMETHROWER = 253;
let ITEM_TESLA_GUN = 254;
let ITEM_SNOWBALL_GUN = 255;
let ITEM_FREEZE_GUN = 256;
let ITEM_PRESENT_LAUNCHER = 257;
let ITEM_KRAMPUS_CHAIN = 258;
let ITEM_BLIZZARD_STAFF = 259;
let ITEM_SNOWBALL = 300;
let ITEM_PRESENT = 301;
let ITEM_TEDDY_BEAR = 170;
let ITEM_TOY_TRAIN = 171;
let ITEM_BALL = 172;
let ITEM_RUBBER_DUCK = 173;
let ITEM_TOY_SOLDIER = 174;
let ITEM_SNOW_GLOBE = 175;
let ITEM_EYEBALL_SOUP = 176;
let ITEM_BLOOD_PISTOL = 260;
let ITEM_BLOOD_DUAL_SHOTGUNS = 261;
let ITEM_BEER = 777;
let ITEM_PUMPKIN_JUICE = 778;
let ITEM_PUMPKIN_SHIELD = 779;
let ITEM_PUMPKIN = 780;
let ITEM_CANDY_GUN = 782;
let ITEM_PUMPKIN_GUN = 783;
let ITEM_CANDY = 781;
let ITEM_CANDY_RED = 784;
let ITEM_CANDY_GREEN = 785;
let ITEM_CANDY_BLUE = 786;
let ITEM_CANDY_CYAN = 788;
let ITEM_CANDY_MAGENTA = 789;
let ITEM_BOSSIFIER_VAMPIRE = 790;
let ITEM_BAT_BLASTER = 791;
let ITEM_LIFESTEAL_STAFF = 792;
let ITEM_BOSSIFIER_NECROMANCER = 793;
let ITEM_NECROMANCER_STAFF = 794;
let ITEM_BOSSIFIER_DEVIL = 795;
let ITEM_FIRE_STAFF = 796;
let ITEMS_CANDIES = [
	ITEM_CANDY,
	ITEM_CANDY_RED,
	ITEM_CANDY_GREEN,
	ITEM_CANDY_BLUE,
	ITEM_CANDY_CYAN,
	ITEM_CANDY_MAGENTA
];
let ITEMS_TOYS = [
	ITEM_TEDDY_BEAR,
	ITEM_TOY_TRAIN,
	ITEM_BALL,
	ITEM_RUBBER_DUCK,
	ITEM_SNOW_GLOBE
];
let ITEMS_BOSSIFIERS = [
	ITEM_BOSSIFIER_REGULAR,
	ITEM_BOSSIFIER_SHOOTING,
	ITEM_BOSSIFIER_RED,
	ITEM_BOSSIFIER_SWORD,
	ITEM_BOSSIFIER_ROCKET,
	ITEM_BOSSIFIER_LASER,
	ITEM_BOSSIFIER_DESERT,
	ITEM_BOSSIFIER_MUMMY,
	ITEM_BOSSIFIER_SHADOW,
	ITEM_BOSSIFIER_ANUBIS,
	ITEM_BOSSIFIER_SNOW,
	ITEM_BOSSIFIER_USHANKA,
	ITEM_BOSSIFIER_SNOWMAN,
	ITEM_BOSSIFIER_KRAMPUS,
	ITEM_BOSSIFIER_BLOOD,
	ITEM_BOSSIFIER_PUMPKIN_SKELETON,
	ITEM_BOSSIFIER_VAMPIRE,
	ITEM_BOSSIFIER_NECROMANCER,
	ITEM_BOSSIFIER_DEVIL
];
let ITEMS_JUNK = [
	ITEM_APPLE_CORE,
	ITEM_FISH_BONE,
	ITEM_EMPTY_BOTTLE,
	ITEM_TIN_CAN,
	ITEM_OLD_SHOE,
	ITEM_CRUMPLED_PAPER,
	ITEM_DEAD_BATTERY
];
ITEMS_AMMOS = [
	ITEM_AMMO,
	ITEM_PLASMA,
	ITEM_RED_PLASMA,
	ITEM_ROCKET,
	ITEM_RAINBOW_AMMO,
	ITEM_VENOM,
	ITEM_SNOWBALL,
	ITEM_PRESENT,
	ITEM_PUMPKIN,
	ITEM_CANDY,
	ITEM_CANDY_RED,
	ITEM_CANDY_GREEN,
	ITEM_CANDY_BLUE,
	ITEM_CANDY_CYAN,
	ITEM_CANDY_MAGENTA
];
ITEMS_GUNS = [
	ITEM_GUN,
	ITEM_DESERT_EAGLE,
	ITEM_SHOTGUN,
	ITEM_MINIGUN,
	ITEM_PLASMA_LAUNCHER,
	ITEM_PLASMA_PISTOL,
	ITEM_REVOLVER,
	ITEM_KALASHNIKOV,
	ITEM_RED_PISTOLS,
	ITEM_RED_SHOTGUN,
	ITEM_MUMMY_PISTOLS,
	ITEM_MUMMY_SHOTGUN,
	ITEM_GREEN_GUN,
	ITEM_SHADOW_STAFF,
	ITEM_SHADOW_DUAL_SHOTGUNS,
	ITEM_ROCKET_LAUNCHER,
	ITEM_ROCKET_SHOTGUN,
	ITEM_ANUBIS_SANDSTORM_STAFF,
	ITEM_ANUBIS_PUNISHER_ROD,
	ITEM_RAINBOW_PISTOLS,
	ITEM_LASER_GUN,
	ITEM_JUNK_CANNON,
	ITEM_SNAKE_STAFF,
	ITEM_VENOM_DUAL_SHOTGUNS,
	ITEM_PP_SH,
	ITEM_MOSIN_RIFLE,
	ITEM_ROCKET_PISTOL,
	ITEM_FLAMETHROWER,
	ITEM_TESLA_GUN,
	ITEM_SNOWBALL_GUN,
	ITEM_FREEZE_GUN,
	ITEM_PRESENT_LAUNCHER,
	ITEM_KRAMPUS_CHAIN,
	ITEM_BLIZZARD_STAFF,
	ITEM_BLOOD_PISTOL,
	ITEM_BLOOD_DUAL_SHOTGUNS,
	ITEM_CANDY_GUN,
	ITEM_PUMPKIN_GUN,
	ITEM_BAT_BLASTER,
	ITEM_LIFESTEAL_STAFF,
	ITEM_NECROMANCER_STAFF,
	ITEM_FIRE_STAFF
];
ITEMS_MELEE = [
	ITEM_STICK,
	ITEM_SWORD,
	ITEM_HORN
];
ITEMS_FOODS = [
	ITEM_CANNED_MEAT,
	ITEM_ORANGE,
	ITEM_APPLE,
	ITEM_CHICKEN_LEG,
	ITEM_CHOCOLATE,
	ITEM_HONEY,
	ITEM_EYEBALL_SOUP
];
ITEMS_DRINKS = [
	ITEM_WATER,
	ITEM_COLA,
	ITEM_MILK,
	ITEM_CACTUS_JUICE,
	ITEM_BEER,
	ITEM_PUMPKIN_JUICE,
];